site_name: Addons by Viz Life Studio
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - toc.follow
    - navigation.top

nav:
  - Home: index.md
  - zForm: zForm/overview.md
  - Depth Map Batch: DepthMapBatch/overview.md

extra_css:
  - overrides.css

